from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

class PipelineMetrics(BaseModel):
    """
    Standardized payload capturing execution durations and performance statistics
    across all stages of the stock agent RAG pipeline.
    """
    total_duration_ms: float = Field(0.0, description="Full request lifecycle duration in milliseconds.")
    retrieval_duration_ms: float = Field(0.0, description="Duration of the hybrid news retrieval stage in milliseconds.")
    reranker_duration_ms: float = Field(0.0, description="Duration of the Cross-Encoder reranking stage in milliseconds.")
    grounding_duration_ms: float = Field(0.0, description="Duration of the grounding rules check stage in milliseconds.")
    prompt_build_duration_ms: float = Field(0.0, description="Duration of context prompting formatting in milliseconds.")
    llm_duration_ms: float = Field(0.0, description="Duration of LLM query execution and response fetching in milliseconds.")

    chunks_retrieved: int = Field(0, description="Number of news document candidate chunks fetched during retrieval.")
    chunks_after_rerank: int = Field(0, description="Number of candidate chunks kept after cross-encoder reranking.")
    grounded: bool = Field(False, description="Flag indicating if the query passed all grounding rules.")
    model_name: Optional[str] = Field(None, description="The name of the LLM model invoked (e.g. phi3:mini).")

    # Future compatibility additions
    tokens_generated: Optional[int] = Field(None, description="Number of output tokens generated by the LLM.")
    prompt_tokens: Optional[int] = Field(None, description="Number of input tokens sent to the LLM.")
    completion_tokens: Optional[int] = Field(None, description="Number of output tokens returned in response.")
    ttft_ms: Optional[float] = Field(None, description="Time to first token in milliseconds.")
    cost: Optional[float] = Field(None, description="Quantitative cost computed for API models.")

    # Extensibility catch-all dictionary
    additional_data: Dict[str, Any] = Field(default_factory=dict, description="Custom debugging metadata dictionary.")
